version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    command: yarn start
  mongo:
    image: mongo:4.4.8
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb-data:
